apiVersion: v1
kind: Pod
metadata:
  name: vinagre
  namespace: default
  labels:
    app: nginx
spec:
  containers:
  - name: girus
    image: nginx
    ports:
    - containerPort: 80
    resources:
      limits:
        cpu: 0.5
        memory: 128Mi
      requests:
        cpu: 0.25    
        memory: 64Mi



